version: "2"

services:
  webserver:
    build: "./apache-php"
    links:
      - mysql
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - "./public_html/:${APACHE_DOCUMENT_ROOT}"
      - "./logs/apache2/:/var/log/apache2/"
      - "./share/:/home/share/"

        
  mysql:
    image: mysql:5.7.40
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}