version: "2"

services:
  webserver:
    build: "./apache-php"
    links:
      - mysql
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - "${HOST_APACHE_WEBROOT}:${APACHE_WEBROOT}"
      - "./logs/apache2/:${APACHE_LOG_DIR}"
      - "./share/:/home/share/"

        
  mysql:
    image: ${MYSQL_DATABASE_IMAGE_VER}
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}